# -*- coding: utf-8 -*-
"""api_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kh58vhvJJ81EEP22dvgUMqNoGwBxpRPZ
"""

import requests
import json
import math
import os
from geopy.geocoders import Nominatim # 這是把地名轉經緯度的套件 (需 pip install geopy)

def latlon_to_tile_xy(lat, lon, zoom=11):
    # 座標轉換公式，用來算出 X, Y
    n = 2.0 ** zoom
    xtile = int((lon + 180.0) / 360.0 * n)
    ytile = int((1.0 - math.asinh(math.tan(math.radians(lat))) / math.pi) / 2.0 * n)
    return xtile, ytile

#location_name:中文或英文
def get_taipei_historical_info(location_name: str) -> str:
    # 將地名轉為經緯度 (模擬查 Google Map)
    geolocator = Nominatim(user_agent="taipei_history_bot")
    location = geolocator.geocode(f"台北市 {location_name}")

    if not location:
        return json.dumps({"error": f"找不到 {location_name} 的座標"})

    lat, lon = location.latitude, location.longitude

    # 轉換為 ArcGIS 的圖磚 X, Y 座標
    zoom_level = 16 # 越高等越詳細
    x, y = latlon_to_tile_xy(lat, lon, zoom_level)

    # 組裝不同年份的網址
    base_url = "https://www.historygis.udd.gov.taipei/arcgis/rest/services/Aerial/{layer}/MapServer/tile/{z}/{y}/{x}"

    result = {
        "status": "success",
        "location": location_name,
        "zoom": zoom_level,
        "historical_images": {
            "1979": base_url.format(layer="Ortho_1979_2", z=zoom_level, y=y, x=x),
            "2005": base_url.format(layer="Ortho_2005", z=zoom_level, y=y, x=x),
            "2023": base_url.format(layer="Ortho_2023", z=zoom_level, y=y, x=x)
        }
    }

    # 把字典轉成 JSON 字串，交還給 Agent
    return json.dumps(result)

# 測試區塊
if __name__ == "__main__":
    print(" 測試開始：呼叫 API 工具...")

    # 模擬 Agent 呼叫函數
    test_location = "捷運動物園站"
    json_result = get_taipei_historical_info(test_location)

    print("\n Agent 收到的 JSON 回傳值：")
    print(json_result)

    # 將 JSON 字串轉回 Python 字典以方便讀取
    data = json.loads(json_result)

    if "error" in data:
        print(f"\n 發生錯誤: {data['error']}")
    else:
        print(f"\n 成功算出圖磚座標！準備模擬 Agent 下載圖片進行驗證...")

        # 建立一個資料夾來放測試圖
        os.makedirs("agent_test_images", exist_ok=True)

        # 模擬下載時，破解防盜連的 Headers
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36",
            "Referer": "https://www.historygis.udd.gov.taipei/"
        }

        # 3. 迴圈讀取 JSON 裡面的每一個年份與網址
        for year, url in data["historical_images"].items():
            print(f"\n⬇ 正在驗證 {year} 年的網址: {url}")
            try:
                # 發送請求去抓圖
                response = requests.get(url, headers=headers, timeout=10)

                # 檢查是否成功且真的是圖片
                if response.status_code == 200 and 'image' in response.headers.get('Content-Type', ''):
                    # 存檔檢查
                    filename = f"agent_test_images/{test_location}_{year}.jpg"
                    with open(filename, 'wb') as f:
                        f.write(response.content)
                    print(f" 成功！圖片已存至: {filename}")
                else:
                    print(f" 失敗！這串網址抓不到圖片。狀態碼: {response.status_code}")
                    print(f"回傳內容類型: {response.headers.get('Content-Type')}")

            except Exception as e:
                print(f" 網路請求發生錯誤: {e}")

    print("\n 測試結束！去左側資料夾看看圖片長怎樣")

import requests
import re

def fetch_wmts_tile_auto(layer_id, z, x, y, output_filename):
    """
    動態解析 WMTS XML 目錄，自動找出該圖層的真實 RESTful 路徑並下載
    """
    # 取得服務目錄清單
    caps_url = "https://www.historygis.udd.gov.taipei/WMTS/"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
        "Referer": "https://historygis.udd.gov.taipei/"
    }

    print("向伺服器索取總目錄清單...")
    try:
        res = requests.get(caps_url, headers=headers)
        if res.status_code != 200:
            print("無法取得目錄，伺服器可能阻擋了連線。")
            return
    except Exception as e:
        print(f"連線失敗：{e}")
        return

    # 2. 找出該圖層專屬的 RESTful 模板網址
    print(f"正在解析圖層 {layer_id} 的真實路徑...")

    # 為了避免跨圖層讀取錯誤，用 <Layer> 標籤把 XML 切開
    layers_data = res.text.split("<Layer>")
    target_template = None

    for layer_xml in layers_data:
        # 如果這個區塊裡面有 Layer ID
        if f"<ows:Identifier>{layer_id}</ows:Identifier>" in layer_xml:
            # 把 template="..." 裡面的網址抓出來
            match = re.search(r'template="([^"]+)"', layer_xml)
            if match:
                target_template = match.group(1)
                break

    if not target_template:
        print(f"失敗：在伺服器的目錄中找不到圖層 {layer_id} 的網址格式！")
        return

    print(f"找到伺服器規定的模板：\n   {target_template}")

    # 替換掉括號裡的變數
    final_url = target_template.replace("{Style}", "default") \
                               .replace("{TileMatrixSet}", "GoogleMapsCompatible") \
                               .replace("{TileMatrix}", str(z)) \
                               .replace("{TileRow}", str(y)) \
                               .replace("{TileCol}", str(x))

    print(f"最終網址: {final_url}")

    # 真正去下載圖片
    try:
        img_res = requests.get(final_url, headers=headers)

        if img_res.status_code == 200 and 'image' in img_res.headers.get('Content-Type', ''):
            with open(output_filename, 'wb') as f:
                f.write(img_res.content)
            print(f"圖片成功下載並儲存至：{output_filename}")
        else:
            print(f"圖片下載失敗。狀態碼: {img_res.status_code}")
            print(f"伺服器回應：{img_res.text[:200]}")
    except Exception as e:
        print(f"下載圖片時發生錯誤：{e}")

# ===== 測試執行 =====
if __name__ == "__main__":
    zoom = 15
    tile_x = 27448
    tile_y = 14032

    # 測試下載影像圖
    fetch_wmts_tile_auto("DGN_M111", zoom, tile_x, tile_y, "test.png")

#https://www.historygis.udd.gov.taipei/arcgis/rest/services/TOPO/DGN_2025/MapServer/WMTS/tile/1.0.0/TOPO_DGN_2025/default/GoogleMapsCompatible/15/14032/27448.png 最新版地圖(114年版地形圖)
#https://www.historygis.udd.gov.taipei/arcgis/rest/services/TOPO/DGN_2024/MapServer/WMTS/tile/1.0.0/TOPO_DGN_2024/default/GoogleMapsCompatible/15/14032/27448.png
#https://www.historygis.udd.gov.taipei/arcgis/rest/services/Aerial/Ortho_2025/MapServer/WMTS/tile/1.0.0/Aerial_Ortho_2025/default/GoogleMapsCompatible/15/14032/27448
#https://www.historygis.udd.gov.taipei/arcgis/rest/services/TOPO/DGN_2022/MapServer/WMTS/tile/1.0.0/TOPO_DGN_2022/default/GoogleMapsCompatible/15/14032/27448.png
#https://www.historygis.udd.gov.taipei/UDDWMTS/tile/Image_Image_1945_B/15/14032/27448